function sortedEntries(obj) {
  return Object.entries(obj).sort((a, b) => b[1] - a[1]);
}

function bar(value, max, width = 20) {
  const len = Math.max(1, Math.round((value / max) * width));
  return '█'.repeat(len) + '░'.repeat(width - len);
}

export function formatText(analysis, { daysBack = 7, language = null } = {}) {
  const lines = [];
  const { topRepos, languages, topics, licenses, stats } = analysis;

  // Header
  const scope = language ? ` (${language})` : '';
  lines.push(`\x1b[1mGitHub Pulse — last ${daysBack} days${scope}\x1b[0m`);
  lines.push('');

  // Stats
  lines.push(`  ${stats.count} repos | ★ avg ${stats.avgStars} | ★ max ${stats.maxStars}`);
  lines.push('');

  // Top repos
  lines.push('\x1b[1mTop repos\x1b[0m');
  for (const r of topRepos) {
    const lang = r.language ? `\x1b[33m${r.language}\x1b[0m` : '';
    lines.push(`  ★ ${String(r.stars).padStart(5)} ${r.name} ${lang}`);
    if (r.description) {
      lines.push(`\x1b[2m         ${r.description.slice(0, 80)}\x1b[0m`);
    }
  }
  lines.push('');

  // Languages
  const langEntries = sortedEntries(languages);
  if (langEntries.length > 0) {
    const maxLang = langEntries[0][1];
    lines.push('\x1b[1mLanguages\x1b[0m');
    for (const [lang, count] of langEntries.slice(0, 10)) {
      lines.push(`  ${bar(count, maxLang)} ${lang} (${count})`);
    }
    lines.push('');
  }

  // Topics
  const topicEntries = sortedEntries(topics);
  if (topicEntries.length > 0) {
    lines.push('\x1b[1mHot topics\x1b[0m');
    lines.push(`  ${topicEntries.slice(0, 15).map(([t, c]) => `${t}(${c})`).join('  ')}`);
    lines.push('');
  }

  // Licenses
  const licEntries = sortedEntries(licenses);
  if (licEntries.length > 0) {
    lines.push('\x1b[1mLicenses\x1b[0m');
    lines.push(`  ${licEntries.slice(0, 8).map(([l, c]) => `${l}(${c})`).join('  ')}`);
    lines.push('');
  }

  return lines.join('\n');
}

export function formatMarkdown(analysis, { daysBack = 7, language = null } = {}) {
  const lines = [];
  const { topRepos, languages, topics, stats } = analysis;

  const scope = language ? ` (${language})` : '';
  lines.push(`# GitHub Pulse — last ${daysBack} days${scope}`);
  lines.push('');
  lines.push(`${stats.count} trending repos | avg ★${stats.avgStars} | max ★${stats.maxStars}`);
  lines.push('');

  // Top repos table
  lines.push('## Top Repos');
  lines.push('');
  lines.push('| Stars | Repo | Language | Description |');
  lines.push('| ---: | --- | --- | --- |');
  for (const r of topRepos) {
    const desc = (r.description || '').slice(0, 60) + ((r.description || '').length > 60 ? '...' : '');
    lines.push(`| ★${r.stars} | [${r.name}](${r.url}) | ${r.language || '-'} | ${desc} |`);
  }
  lines.push('');

  // Languages
  const langEntries = sortedEntries(languages);
  if (langEntries.length > 0) {
    lines.push('## Languages');
    lines.push('');
    lines.push('| Language | Count |');
    lines.push('| --- | ---: |');
    for (const [lang, count] of langEntries.slice(0, 10)) {
      lines.push(`| ${lang} | ${count} |`);
    }
    lines.push('');
  }

  // Topics
  const topicEntries = sortedEntries(topics);
  if (topicEntries.length > 0) {
    lines.push('## Hot Topics');
    lines.push('');
    lines.push(topicEntries.slice(0, 15).map(([t, c]) => `\`${t}\`(${c})`).join(' · '));
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated by gh-pulse at ${new Date().toISOString().slice(0, 16)}*`);

  return lines.join('\n');
}

export function formatJson(analysis) {
  return JSON.stringify(analysis, null, 2);
}
